sudo: required

before_install:
        sudo apt-get -qq update
        sudo apt-get install -y libsystemd-dev

language: erlang

otp_release:
        - 18.0

script: "./rebar compile && ./rebar skip_deps=true eunit"
