sudo: required
dist: trusty

notifications:
          email: false

before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y libsystemd-daemon-dev

language: erlang

otp_release:
        - 18.0

script: "./rebar compile && ./rebar skip_deps=true eunit"
